- name: "HIGH | RHEL-07-010260 | PATCH | The system must not have accounts configured with blank or null passwords."
  replace:
      dest: /etc/pam.d/system-auth
      regexp: 'nullok ?'
  tags:
      - cat1
      - high
      - patch
      - RHEL-07-010260

- name: "HIGH | RHEL-07-010270 | PATCH | The SSH daemon must not allow authentication using an empty password."
  lineinfile:
      state: present
      dest: /etc/ssh/sshd_config
      regexp: ^#?PermitEmptyPasswords
      line: PermitEmptyPasswords no
      validate: sshd -tf %s
  notify: restart sshd
  tags:
      - cat1
      - high
      - patch
      - RHEL-07-010270
      - sshd

- name: "HIGH | RHEL-07-021910 | PATCH | The telnet-server package must not be installed."
  command: "true"
  tags:
      - cat1
      - high
      - patch
      - RHEL-07-021910

- name: "HIGH | RHEL-07-020000 | PATCH | The rsh-server package including rexecd and rlogind must not be installed."
  command: "true"
  tags:
      - cat1
      - high
      - patch
      - RHEL-07-020000

- name: "HIGH | RHEL-07-020010 | PATCH | The ypserv package must not be installed."
  command: "true"
  tags:
      - cat1
      - high
      - patch
      - RHEL-07-020010

- name: "HIGH | RHEL-07-020220 | PATCH | The x86 Ctrl-Alt-Delete key sequence must be disabled."
  command: "true"
  tags:
      - cat1
      - high
      - patch
      - RHEL-07-020220

- name: "HIGH | RHEL-07-010430 | PATCH | The operating system must not allow an unattended or automatic logon to the system."
  command: "true"
  tags:
      - cat1
      - high
      - patch
      - RHEL-07-010430

- name: "HIGH | RHEL-07-020240 | PATCH | The operating system must be a supported release."
  command: "true"
  tags:
      - cat1
      - high
      - patch
      - RHEL-07-020240

- name: "HIGH | RHEL-07-020310 | PATCH | The root account must be the only account having unrestricted access to the system."
  command: "true"
  tags:
      - cat1
      - high
      - patch
      - RHEL-07-020310

- name: "HIGH | RHEL-07-020730 | PATCH | Run control scripts must not execute world-writable programs or scripts."
  command: "true"
  tags:
      - cat1
      - high
      - patch
      - RHEL-07-020730

- name: "HIGH | RHEL-07-040330 | PATCH | There must be no .rhosts, .shosts, rhosts.equiv, or shosts.equiv files on the system."
  command: "true"
  tags:
      - cat1
      - high
      - patch
      - RHEL-07-040330

- name: "HIGH | RHEL-07-040340 | PATCH | PAM must not support rsh server authentication."
  command: "true"
  tags:
      - cat1
      - high
      - patch
      - RHEL-07-040340

- name: "HIGH | RHEL-07-020930 | PATCH | All shell files must have mode 0755 or less permissive."
  command: "true"
  tags:
      - cat1
      - high
      - patch
      - RHEL-07-020930

- name: "HIGH | RHEL-07-021350 | PATCH | Privileged accounts on the system must not utilize a web browser on the system, with the exception to access webpages used of administration of applications on the system."
  command: "true"
  tags:
      - cat1
      - high
      - patch
      - RHEL-07-021350

- name: "HIGH | RHEL-07-021360 | PATCH | Files executed through a mail aliases file must be owned by root."
  command: "true"
  tags:
      - cat1
      - high
      - patch
      - RHEL-07-021360

- name: "HIGH | RHEL-07-021370 | PATCH | Files executed through a mail aliases file must reside within a directory owned and writable only by root."
  command: "true"
  tags:
      - cat1
      - high
      - patch
      - RHEL-07-021370

- name: "HIGH | RHEL-07-021420 | PATCH | The SMTP server must be the latest version available from operating system vendor."
  command: "true"
  tags:
      - cat1
      - high
      - patch
      - RHEL-07-021420

- name: "HIGH | RHEL-07-040490 | PATCH | A ftp server package must not be installed."
  command: "true"
  tags:
      - cat1
      - high
      - patch
      - RHEL-07-040490

- name: "HIGH | RHEL-07-040500 | PATCH | The TFTP server package must not be installed if not required for operational support."
  command: "true"
  tags:
      - cat1
      - high
      - patch
      - RHEL-07-040500

- name: "HIGH | RHEL-07-040540 | PATCH | Remote X connections for interactive users must be encrypted."
  command: "true"
  tags:
      - cat1
      - high
      - patch
      - RHEL-07-040540

- name: "HIGH | RHEL-07-040550 | PATCH | X Windows displays must not be exported to the world."
  command: "true"
  tags:
      - cat1
      - high
      - patch
      - RHEL-07-040550

- name: "HIGH | RHEL-07-040570 | PATCH | The UUCP package must not be installed."
  command: "true"
  tags:
      - cat1
      - high
      - patch
      - RHEL-07-040570

- name: "HIGH | RHEL-07-040580 | PATCH | SNMP community strings must be changed from the default."
  command: "true"
  tags:
      - cat1
      - high
      - patch
      - RHEL-07-040580

- name: "HIGH | RHEL-07-040590 | PATCH | The SSH daemon must be configured to only use the SSHv2 protocol."
  command: "true"
  tags:
      - cat1
      - high
      - patch
      - RHEL-07-040590

- name: "HIGH | RHEL-07-040770 | PATCH | The samba service must not use the smbpasswd authentication method."
  command: "true"
  tags:
      - cat1
      - high
      - patch
      - RHEL-07-040770

- name: "HIGH | RHEL-07-040800 | PATCH | Samba must be configured to use encrypted passwords."
  command: "true"
  tags:
      - cat1
      - high
      - patch
      - RHEL-07-040800

- name: "HIGH | RHEL-07-030810 | PATCH | The system must use a DoD-approved virus scan program."
  command: "true"
  tags:
      - cat1
      - high
      - patch
      - RHEL-07-030810

- name: "HIGH | RHEL-07-021770 | PATCH | The system boot loader must require authentication."
  command: "true"
  tags:
      - cat1
      - high
      - patch
      - RHEL-07-021770

- name: "HIGH | RHEL-07-021840 | PATCH | The system must not have extraneous accounts with special privileges, such as shutdown, halt, and reboot."
  command: "true"
  tags:
      - cat1
      - high
      - patch
      - RHEL-07-021840
